<?php include('../inc/header.php'); ?>
	<section class="col-2-3 center">
		<header><h2>About Me</h2></header>
		<article>
		<header><h3>Becoming a Developer</h3></header>
			<p>My journey as a developer has been a long and winding road. When I was a child, my dad brought home a Commodore 64 and a Compute Gazette subscription. I watched him and a friend spend hours typing in strings of letters and numbers, eventually outputting a working program (but more often going blind searching through lines of code for the mistake that broke the whole thing). He taught me to control a turtle with LOGO, and to build simple software with BASIC and GOTO statements. As a teen, I'd write simple quizzes to study for tests. But I never thought I had the capacity for computer science when my other AP buddies were writing games on their TI-81s.</p>
			<p>The internet hit mainstream just as I was graduating high school. I was fascinated by my newfound access to the knowledge of the universe. I eagerly surfed the web, navigated web-rings and joined interest based email discussion lists. In 2002, I built my first website. I didn't know anything about servers or hosting, but my ISP offered a little space for a home page. I downloaded an open source WYSWIG editor called Arachnophilia. By clicking between code view and rendered view, I began to decipher the HTML and inline styles. My pages had falling snowflakes and confetti that trailed behind my cursor. So beautiful! But what I really wanted was the ability to use fancy fonts I had installed on my computer through my PrintMaster program. Uploading and linking to the files like I would an image didn't work.</p>
			<p>Using my newly acquired skills, I built a new website for my midwife. She had some existing assets she wanted to maintain, but every page was a different color and a different layout. And I first encountered tables! I did the best I could to increase functionality, establish a modicum of consistency and make content readable.</p>
			<p>I started hanging around discussion boards, and soon witnessed members disappearing to start web-logging. Eventually I followed their lead, and a virtual friend introduced me to Wordpress 1.0. Instantly, I envisioned the capacity of this software for creating websites. I'd never figured out how to link HTML to CSS. I wasn't designing actively enough to pursue learning more, as I was homeschooling as well as becoming a doula and student midwife. But Wordpress allowed me to work around that deficiency by installing a pre-built template that I could modify to my heart's content through the code editor. I built websites for non-profits I was involved with, and as barters for midwifery and chiropractic care. I built websites for family members launching their own businesses, and they encouraged me to start my own business.</p>
			<p>While I didn't know any PHP, I dove in and moved code around, broke and fixed plenty of things, and was able to do some unique things programmatically. I started learning how to build themes using online tutorials, and was thrilled to discover how to overlap two images using positioning, something I struggled with in table layout. I took on a job for a statewide non-profit organization with hundreds of members, whose members were not, on the whole, very computer savvy. While most people seemed to figure out how to navigate through a Wordpress website by clicking titles to view comments to articles, this seemed to stymie enough of them that they wanted significant changes to the way a theme generally functioned. Not only that, but they also wanted members to post from the front-end, not the back-end. And when they logged in, they should return to the page from which they logged in, not landing at the admin panel. While I managed all of these requirements, I knew I was not charging enough and I was frustrated by not actually understanding the code that I was so freely manipulating. I knew I had to go to school to fill the gaps that my need to know self-education had left.</p>
			<p>I dove in head first, as I usually do--I blame my parents, aunts and uncles for teaching me to swim this way--and finished a two year degree with a one year entrepreneurship certificate program tacked on, in fourteen months, achieving Program Student of the Year status to boot. While I love helping my clients launch their first business websites, I have a desire to go further and build more extensive projects. My education launched me into a vast ocean with some little water wings for support.</p>
		</article>
	</section>
<?php include('../inc/footer.php'); ?>